//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolBox {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\Testing\\APKs")]
        public string ApkDirectory {
            get {
                return ((string)(this["ApkDirectory"]));
            }
            set {
                this["ApkDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\Testing\\ADB commands\\Logcat")]
        public string LogCatSaveDirectory {
            get {
                return ((string)(this["LogCatSaveDirectory"]));
            }
            set {
                this["LogCatSaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\Testing\\ADB commands\\applogs")]
        public string DeviceAppLogSaveDirectory {
            get {
                return ((string)(this["DeviceAppLogSaveDirectory"]));
            }
            set {
                this["DeviceAppLogSaveDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"host=local|10.9.10.12  org=seth|seth  d=uwarbear|aaaa d=aavenicci|aaaa d=jbalgruuf|aaaa d=egraymane|aaaa d=kwhitemane|aaaa d=dpurespring|aaaa d=cvalentia|aaaa d=pavenicci|aaaa d=obattleborn|aaaa d=fsecretfire|aaaa~host=epsilon|epsilonmobile.iseinc.biz  org=seth|seth  d=nick|aaaa d=danse|aaaa d=preston|aaaa d=kellogg|aaaa d=tinkertom|aaaa d=piper|aaaa org=sethOrg|SETH1234  d=driver1|aaaa d=driver2|aaaa d=driver3|aaaa d=driver4|aaaa")]
        public string ProvisioningHosts {
            get {
                return ((string)(this["ProvisioningHosts"]));
            }
            set {
                this["ProvisioningHosts"] = value;
            }
        }
    }
}
